"""Initial migration

Revision ID: 820eea6d9883
Revises: 
Create Date: 2026-01-05 17:28:02.733216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820eea6d9883'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('language_preference', sa.String(length=10), nullable=False),
    sa.Column('max_devices', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_id'), 'businesses', ['id'], unique=False)
    op.create_index(op.f('ix_businesses_name'), 'businesses', ['name'], unique=False)
    op.create_index(op.f('ix_businesses_phone'), 'businesses', ['phone'], unique=True)
    op.create_table('users',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('audit_logs',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_business_action_timestamp', 'audit_logs', ['business_id', 'action', 'timestamp'], unique=False)
    op.create_index('ix_audit_logs_business_entity', 'audit_logs', ['business_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_business_id'), 'audit_logs', ['business_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('backups',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('backup_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('backup_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backups_backup_date'), 'backups', ['backup_date'], unique=False)
    op.create_index(op.f('ix_backups_backup_type'), 'backups', ['backup_type'], unique=False)
    op.create_index('ix_backups_business_date', 'backups', ['business_id', 'backup_date'], unique=False)
    op.create_index(op.f('ix_backups_business_id'), 'backups', ['business_id'], unique=False)
    op.create_index('ix_backups_business_status', 'backups', ['business_id', 'status'], unique=False)
    op.create_index(op.f('ix_backups_id'), 'backups', ['id'], unique=False)
    op.create_index(op.f('ix_backups_status'), 'backups', ['status'], unique=False)
    op.create_table('bank_accounts',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.Column('account_number', sa.String(length=100), nullable=True),
    sa.Column('account_holder_name', sa.String(length=255), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('ifsc_code', sa.String(length=50), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bank_accounts_business_active', 'bank_accounts', ['business_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_bank_accounts_business_id'), 'bank_accounts', ['business_id'], unique=False)
    op.create_index(op.f('ix_bank_accounts_id'), 'bank_accounts', ['id'], unique=False)
    op.create_table('cash_balances',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_cash_in', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_cash_out', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'date')
    )
    op.create_index(op.f('ix_cash_balances_business_id'), 'cash_balances', ['business_id'], unique=False)
    op.create_index(op.f('ix_cash_balances_date'), 'cash_balances', ['date'], unique=False)
    op.create_index(op.f('ix_cash_balances_id'), 'cash_balances', ['id'], unique=False)
    op.create_table('cash_transactions',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('CASH_IN', 'CASH_OUT', name='cashtransactiontype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cash_transactions_business_date', 'cash_transactions', ['business_id', 'date'], unique=False)
    op.create_index(op.f('ix_cash_transactions_business_id'), 'cash_transactions', ['business_id'], unique=False)
    op.create_index('ix_cash_transactions_business_type_date', 'cash_transactions', ['business_id', 'transaction_type', 'date'], unique=False)
    op.create_index(op.f('ix_cash_transactions_date'), 'cash_transactions', ['date'], unique=False)
    op.create_index(op.f('ix_cash_transactions_id'), 'cash_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_cash_transactions_transaction_type'), 'cash_transactions', ['transaction_type'], unique=False)
    op.create_table('customers',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customers_business_active', 'customers', ['business_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_customers_business_id'), 'customers', ['business_id'], unique=False)
    op.create_index('ix_customers_business_name', 'customers', ['business_id', 'name'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_table('devices',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('fcm_token', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_cursor', sa.String(length=255), nullable=True),
    sa.Column('pairing_token', sa.String(length=255), nullable=True),
    sa.Column('pairing_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'device_id')
    )
    op.create_index(op.f('ix_devices_business_id'), 'devices', ['business_id'], unique=False)
    op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=True)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_index(op.f('ix_devices_pairing_token'), 'devices', ['pairing_token'], unique=False)
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('expense_categories',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_expense_categories_business_active', 'expense_categories', ['business_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_expense_categories_business_id'), 'expense_categories', ['business_id'], unique=False)
    op.create_index('ix_expense_categories_business_name', 'expense_categories', ['business_id', 'name'], unique=False)
    op.create_index(op.f('ix_expense_categories_id'), 'expense_categories', ['id'], unique=False)
    op.create_index(op.f('ix_expense_categories_name'), 'expense_categories', ['name'], unique=False)
    op.create_table('items',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('unit', sa.Enum('PIECE', 'KILOGRAM', 'LITER', 'METER', 'BOX', 'PACK', name='itemunit'), nullable=False),
    sa.Column('opening_stock', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('current_stock', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('min_stock_threshold', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_barcode'), 'items', ['barcode'], unique=False)
    op.create_index('ix_items_business_active', 'items', ['business_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_items_business_id'), 'items', ['business_id'], unique=False)
    op.create_index('ix_items_business_name', 'items', ['business_id', 'name'], unique=False)
    op.create_index(op.f('ix_items_current_stock'), 'items', ['current_stock'], unique=False)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.create_index(op.f('ix_items_sku'), 'items', ['sku'], unique=False)
    op.create_table('reminders',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reminders_business_entity', 'reminders', ['business_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_reminders_business_id'), 'reminders', ['business_id'], unique=False)
    op.create_index('ix_reminders_business_resolved_due', 'reminders', ['business_id', 'is_resolved', 'due_date'], unique=False)
    op.create_index(op.f('ix_reminders_due_date'), 'reminders', ['due_date'], unique=False)
    op.create_index(op.f('ix_reminders_entity_id'), 'reminders', ['entity_id'], unique=False)
    op.create_index(op.f('ix_reminders_entity_type'), 'reminders', ['entity_type'], unique=False)
    op.create_index(op.f('ix_reminders_id'), 'reminders', ['id'], unique=False)
    op.create_table('staff',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_staff_business_active', 'staff', ['business_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_staff_business_id'), 'staff', ['business_id'], unique=False)
    op.create_index('ix_staff_business_name', 'staff', ['business_id', 'name'], unique=False)
    op.create_index(op.f('ix_staff_id'), 'staff', ['id'], unique=False)
    op.create_index(op.f('ix_staff_name'), 'staff', ['name'], unique=False)
    op.create_index(op.f('ix_staff_phone'), 'staff', ['phone'], unique=False)
    op.create_table('suppliers',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_suppliers_business_active', 'suppliers', ['business_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_suppliers_business_id'), 'suppliers', ['business_id'], unique=False)
    op.create_index('ix_suppliers_business_name', 'suppliers', ['business_id', 'name'], unique=False)
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_index(op.f('ix_suppliers_phone'), 'suppliers', ['phone'], unique=False)
    op.create_table('user_memberships',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MANAGER', 'STAFF', name='userroleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'business_id')
    )
    op.create_index(op.f('ix_user_memberships_business_id'), 'user_memberships', ['business_id'], unique=False)
    op.create_index(op.f('ix_user_memberships_id'), 'user_memberships', ['id'], unique=False)
    op.create_index(op.f('ix_user_memberships_user_id'), 'user_memberships', ['user_id'], unique=False)
    op.create_table('bank_transactions',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('DEPOSIT', 'WITHDRAWAL', 'TRANSFER', name='banktransactiontype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_transactions_bank_account_id'), 'bank_transactions', ['bank_account_id'], unique=False)
    op.create_index('ix_bank_transactions_business_account_date', 'bank_transactions', ['business_id', 'bank_account_id', 'date'], unique=False)
    op.create_index(op.f('ix_bank_transactions_business_id'), 'bank_transactions', ['business_id'], unique=False)
    op.create_index('ix_bank_transactions_business_type_date', 'bank_transactions', ['business_id', 'transaction_type', 'date'], unique=False)
    op.create_index(op.f('ix_bank_transactions_date'), 'bank_transactions', ['date'], unique=False)
    op.create_index(op.f('ix_bank_transactions_id'), 'bank_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_transaction_type'), 'bank_transactions', ['transaction_type'], unique=False)
    op.create_table('cash_bank_transfers',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('transfer_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('from_bank_account_id', sa.Integer(), nullable=True),
    sa.Column('to_bank_account_id', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_bank_account_id'], ['bank_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_bank_account_id'], ['bank_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cash_bank_transfers_business_date', 'cash_bank_transfers', ['business_id', 'date'], unique=False)
    op.create_index(op.f('ix_cash_bank_transfers_business_id'), 'cash_bank_transfers', ['business_id'], unique=False)
    op.create_index('ix_cash_bank_transfers_business_type_date', 'cash_bank_transfers', ['business_id', 'transfer_type', 'date'], unique=False)
    op.create_index(op.f('ix_cash_bank_transfers_date'), 'cash_bank_transfers', ['date'], unique=False)
    op.create_index(op.f('ix_cash_bank_transfers_id'), 'cash_bank_transfers', ['id'], unique=False)
    op.create_index(op.f('ix_cash_bank_transfers_transfer_type'), 'cash_bank_transfers', ['transfer_type'], unique=False)
    op.create_table('customer_balances',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('last_transaction_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'customer_id')
    )
    op.create_index(op.f('ix_customer_balances_business_id'), 'customer_balances', ['business_id'], unique=False)
    op.create_index(op.f('ix_customer_balances_customer_id'), 'customer_balances', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_balances_id'), 'customer_balances', ['id'], unique=False)
    op.create_table('customer_transactions',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customer_transactions_business_customer_date', 'customer_transactions', ['business_id', 'customer_id', 'date'], unique=False)
    op.create_index(op.f('ix_customer_transactions_business_id'), 'customer_transactions', ['business_id'], unique=False)
    op.create_index('ix_customer_transactions_business_type_date', 'customer_transactions', ['business_id', 'transaction_type', 'date'], unique=False)
    op.create_index(op.f('ix_customer_transactions_customer_id'), 'customer_transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_transactions_date'), 'customer_transactions', ['date'], unique=False)
    op.create_index(op.f('ix_customer_transactions_id'), 'customer_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_customer_transactions_transaction_type'), 'customer_transactions', ['transaction_type'], unique=False)
    op.create_table('expenses',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payment_mode', sa.Enum('CASH', 'BANK', name='paymentmode'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_expenses_business_category_date', 'expenses', ['business_id', 'category_id', 'date'], unique=False)
    op.create_index('ix_expenses_business_date', 'expenses', ['business_id', 'date'], unique=False)
    op.create_index(op.f('ix_expenses_business_id'), 'expenses', ['business_id'], unique=False)
    op.create_index('ix_expenses_business_payment_date', 'expenses', ['business_id', 'payment_mode', 'date'], unique=False)
    op.create_index(op.f('ix_expenses_category_id'), 'expenses', ['category_id'], unique=False)
    op.create_index(op.f('ix_expenses_date'), 'expenses', ['date'], unique=False)
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_index(op.f('ix_expenses_payment_mode'), 'expenses', ['payment_mode'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('STOCK_IN', 'STOCK_OUT', 'WASTAGE', 'ADJUSTMENT', name='inventorytransactiontype'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transactions_business_id'), 'inventory_transactions', ['business_id'], unique=False)
    op.create_index('ix_inventory_transactions_business_item_date', 'inventory_transactions', ['business_id', 'item_id', 'date'], unique=False)
    op.create_index('ix_inventory_transactions_business_type_date', 'inventory_transactions', ['business_id', 'transaction_type', 'date'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_date'), 'inventory_transactions', ['date'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_id'), 'inventory_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_item_id'), 'inventory_transactions', ['item_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_transaction_type'), 'inventory_transactions', ['transaction_type'], unique=False)
    op.create_table('invoices',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('invoice_type', sa.Enum('CASH', 'CREDIT', name='invoicetype'), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoices_business_customer', 'invoices', ['business_id', 'customer_id'], unique=False)
    op.create_index('ix_invoices_business_date', 'invoices', ['business_id', 'date'], unique=False)
    op.create_index(op.f('ix_invoices_business_id'), 'invoices', ['business_id'], unique=False)
    op.create_index('ix_invoices_business_type_date', 'invoices', ['business_id', 'invoice_type', 'date'], unique=False)
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_invoices_date'), 'invoices', ['date'], unique=False)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_invoice_type'), 'invoices', ['invoice_type'], unique=False)
    op.create_table('low_stock_alerts',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('current_stock', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_low_stock_alerts_business_id'), 'low_stock_alerts', ['business_id'], unique=False)
    op.create_index('ix_low_stock_alerts_business_resolved', 'low_stock_alerts', ['business_id', 'is_resolved'], unique=False)
    op.create_index(op.f('ix_low_stock_alerts_id'), 'low_stock_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_low_stock_alerts_item_id'), 'low_stock_alerts', ['item_id'], unique=False)
    op.create_table('staff_salaries',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payment_mode', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_staff_salaries_business_date', 'staff_salaries', ['business_id', 'date'], unique=False)
    op.create_index(op.f('ix_staff_salaries_business_id'), 'staff_salaries', ['business_id'], unique=False)
    op.create_index('ix_staff_salaries_business_staff_date', 'staff_salaries', ['business_id', 'staff_id', 'date'], unique=False)
    op.create_index(op.f('ix_staff_salaries_date'), 'staff_salaries', ['date'], unique=False)
    op.create_index(op.f('ix_staff_salaries_id'), 'staff_salaries', ['id'], unique=False)
    op.create_index(op.f('ix_staff_salaries_payment_mode'), 'staff_salaries', ['payment_mode'], unique=False)
    op.create_index(op.f('ix_staff_salaries_staff_id'), 'staff_salaries', ['staff_id'], unique=False)
    op.create_table('supplier_balances',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('last_transaction_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'supplier_id')
    )
    op.create_index(op.f('ix_supplier_balances_business_id'), 'supplier_balances', ['business_id'], unique=False)
    op.create_index(op.f('ix_supplier_balances_id'), 'supplier_balances', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_balances_supplier_id'), 'supplier_balances', ['supplier_id'], unique=False)
    op.create_table('supplier_transactions',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_transactions_business_id'), 'supplier_transactions', ['business_id'], unique=False)
    op.create_index('ix_supplier_transactions_business_supplier_date', 'supplier_transactions', ['business_id', 'supplier_id', 'date'], unique=False)
    op.create_index('ix_supplier_transactions_business_type_date', 'supplier_transactions', ['business_id', 'transaction_type', 'date'], unique=False)
    op.create_index(op.f('ix_supplier_transactions_date'), 'supplier_transactions', ['date'], unique=False)
    op.create_index(op.f('ix_supplier_transactions_id'), 'supplier_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_transactions_supplier_id'), 'supplier_transactions', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_transactions_transaction_type'), 'supplier_transactions', ['transaction_type'], unique=False)
    op.create_table('user_roles',
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['user_memberships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('membership_id', 'permission')
    )
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_id'), 'invoice_items', ['id'], unique=False)
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_index('ix_invoice_items_invoice_item', 'invoice_items', ['invoice_id', 'item_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_item_id'), 'invoice_items', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_items_item_id'), table_name='invoice_items')
    op.drop_index('ix_invoice_items_invoice_item', table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_supplier_transactions_transaction_type'), table_name='supplier_transactions')
    op.drop_index(op.f('ix_supplier_transactions_supplier_id'), table_name='supplier_transactions')
    op.drop_index(op.f('ix_supplier_transactions_id'), table_name='supplier_transactions')
    op.drop_index(op.f('ix_supplier_transactions_date'), table_name='supplier_transactions')
    op.drop_index('ix_supplier_transactions_business_type_date', table_name='supplier_transactions')
    op.drop_index('ix_supplier_transactions_business_supplier_date', table_name='supplier_transactions')
    op.drop_index(op.f('ix_supplier_transactions_business_id'), table_name='supplier_transactions')
    op.drop_table('supplier_transactions')
    op.drop_index(op.f('ix_supplier_balances_supplier_id'), table_name='supplier_balances')
    op.drop_index(op.f('ix_supplier_balances_id'), table_name='supplier_balances')
    op.drop_index(op.f('ix_supplier_balances_business_id'), table_name='supplier_balances')
    op.drop_table('supplier_balances')
    op.drop_index(op.f('ix_staff_salaries_staff_id'), table_name='staff_salaries')
    op.drop_index(op.f('ix_staff_salaries_payment_mode'), table_name='staff_salaries')
    op.drop_index(op.f('ix_staff_salaries_id'), table_name='staff_salaries')
    op.drop_index(op.f('ix_staff_salaries_date'), table_name='staff_salaries')
    op.drop_index('ix_staff_salaries_business_staff_date', table_name='staff_salaries')
    op.drop_index(op.f('ix_staff_salaries_business_id'), table_name='staff_salaries')
    op.drop_index('ix_staff_salaries_business_date', table_name='staff_salaries')
    op.drop_table('staff_salaries')
    op.drop_index(op.f('ix_low_stock_alerts_item_id'), table_name='low_stock_alerts')
    op.drop_index(op.f('ix_low_stock_alerts_id'), table_name='low_stock_alerts')
    op.drop_index('ix_low_stock_alerts_business_resolved', table_name='low_stock_alerts')
    op.drop_index(op.f('ix_low_stock_alerts_business_id'), table_name='low_stock_alerts')
    op.drop_table('low_stock_alerts')
    op.drop_index(op.f('ix_invoices_invoice_type'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.drop_index('ix_invoices_business_type_date', table_name='invoices')
    op.drop_index(op.f('ix_invoices_business_id'), table_name='invoices')
    op.drop_index('ix_invoices_business_date', table_name='invoices')
    op.drop_index('ix_invoices_business_customer', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_inventory_transactions_transaction_type'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_item_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_date'), table_name='inventory_transactions')
    op.drop_index('ix_inventory_transactions_business_type_date', table_name='inventory_transactions')
    op.drop_index('ix_inventory_transactions_business_item_date', table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_business_id'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_expenses_payment_mode'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_date'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category_id'), table_name='expenses')
    op.drop_index('ix_expenses_business_payment_date', table_name='expenses')
    op.drop_index(op.f('ix_expenses_business_id'), table_name='expenses')
    op.drop_index('ix_expenses_business_date', table_name='expenses')
    op.drop_index('ix_expenses_business_category_date', table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_customer_transactions_transaction_type'), table_name='customer_transactions')
    op.drop_index(op.f('ix_customer_transactions_id'), table_name='customer_transactions')
    op.drop_index(op.f('ix_customer_transactions_date'), table_name='customer_transactions')
    op.drop_index(op.f('ix_customer_transactions_customer_id'), table_name='customer_transactions')
    op.drop_index('ix_customer_transactions_business_type_date', table_name='customer_transactions')
    op.drop_index(op.f('ix_customer_transactions_business_id'), table_name='customer_transactions')
    op.drop_index('ix_customer_transactions_business_customer_date', table_name='customer_transactions')
    op.drop_table('customer_transactions')
    op.drop_index(op.f('ix_customer_balances_id'), table_name='customer_balances')
    op.drop_index(op.f('ix_customer_balances_customer_id'), table_name='customer_balances')
    op.drop_index(op.f('ix_customer_balances_business_id'), table_name='customer_balances')
    op.drop_table('customer_balances')
    op.drop_index(op.f('ix_cash_bank_transfers_transfer_type'), table_name='cash_bank_transfers')
    op.drop_index(op.f('ix_cash_bank_transfers_id'), table_name='cash_bank_transfers')
    op.drop_index(op.f('ix_cash_bank_transfers_date'), table_name='cash_bank_transfers')
    op.drop_index('ix_cash_bank_transfers_business_type_date', table_name='cash_bank_transfers')
    op.drop_index(op.f('ix_cash_bank_transfers_business_id'), table_name='cash_bank_transfers')
    op.drop_index('ix_cash_bank_transfers_business_date', table_name='cash_bank_transfers')
    op.drop_table('cash_bank_transfers')
    op.drop_index(op.f('ix_bank_transactions_transaction_type'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_date'), table_name='bank_transactions')
    op.drop_index('ix_bank_transactions_business_type_date', table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_business_id'), table_name='bank_transactions')
    op.drop_index('ix_bank_transactions_business_account_date', table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_bank_account_id'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_index(op.f('ix_user_memberships_user_id'), table_name='user_memberships')
    op.drop_index(op.f('ix_user_memberships_id'), table_name='user_memberships')
    op.drop_index(op.f('ix_user_memberships_business_id'), table_name='user_memberships')
    op.drop_table('user_memberships')
    op.drop_index(op.f('ix_suppliers_phone'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_index('ix_suppliers_business_name', table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_business_id'), table_name='suppliers')
    op.drop_index('ix_suppliers_business_active', table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_staff_phone'), table_name='staff')
    op.drop_index(op.f('ix_staff_name'), table_name='staff')
    op.drop_index(op.f('ix_staff_id'), table_name='staff')
    op.drop_index('ix_staff_business_name', table_name='staff')
    op.drop_index(op.f('ix_staff_business_id'), table_name='staff')
    op.drop_index('ix_staff_business_active', table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_reminders_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_entity_type'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_entity_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_due_date'), table_name='reminders')
    op.drop_index('ix_reminders_business_resolved_due', table_name='reminders')
    op.drop_index(op.f('ix_reminders_business_id'), table_name='reminders')
    op.drop_index('ix_reminders_business_entity', table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_items_sku'), table_name='items')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_index(op.f('ix_items_current_stock'), table_name='items')
    op.drop_index('ix_items_business_name', table_name='items')
    op.drop_index(op.f('ix_items_business_id'), table_name='items')
    op.drop_index('ix_items_business_active', table_name='items')
    op.drop_index(op.f('ix_items_barcode'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_expense_categories_name'), table_name='expense_categories')
    op.drop_index(op.f('ix_expense_categories_id'), table_name='expense_categories')
    op.drop_index('ix_expense_categories_business_name', table_name='expense_categories')
    op.drop_index(op.f('ix_expense_categories_business_id'), table_name='expense_categories')
    op.drop_index('ix_expense_categories_business_active', table_name='expense_categories')
    op.drop_table('expense_categories')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_pairing_token'), table_name='devices')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_business_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index('ix_customers_business_name', table_name='customers')
    op.drop_index(op.f('ix_customers_business_id'), table_name='customers')
    op.drop_index('ix_customers_business_active', table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_cash_transactions_transaction_type'), table_name='cash_transactions')
    op.drop_index(op.f('ix_cash_transactions_id'), table_name='cash_transactions')
    op.drop_index(op.f('ix_cash_transactions_date'), table_name='cash_transactions')
    op.drop_index('ix_cash_transactions_business_type_date', table_name='cash_transactions')
    op.drop_index(op.f('ix_cash_transactions_business_id'), table_name='cash_transactions')
    op.drop_index('ix_cash_transactions_business_date', table_name='cash_transactions')
    op.drop_table('cash_transactions')
    op.drop_index(op.f('ix_cash_balances_id'), table_name='cash_balances')
    op.drop_index(op.f('ix_cash_balances_date'), table_name='cash_balances')
    op.drop_index(op.f('ix_cash_balances_business_id'), table_name='cash_balances')
    op.drop_table('cash_balances')
    op.drop_index(op.f('ix_bank_accounts_id'), table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_business_id'), table_name='bank_accounts')
    op.drop_index('ix_bank_accounts_business_active', table_name='bank_accounts')
    op.drop_table('bank_accounts')
    op.drop_index(op.f('ix_backups_status'), table_name='backups')
    op.drop_index(op.f('ix_backups_id'), table_name='backups')
    op.drop_index('ix_backups_business_status', table_name='backups')
    op.drop_index(op.f('ix_backups_business_id'), table_name='backups')
    op.drop_index('ix_backups_business_date', table_name='backups')
    op.drop_index(op.f('ix_backups_backup_type'), table_name='backups')
    op.drop_index(op.f('ix_backups_backup_date'), table_name='backups')
    op.drop_table('backups')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_business_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_business_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_business_action_timestamp', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_businesses_phone'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_name'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_id'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###

